services:
  api:
    build:
      context: ./apps/api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    env_file:
      - ./apps/api/.env
    restart: unless-stopped

  web:
    build:
      context: ./apps/web
    ports:
      - "80:3050"
    restart: unless-stopped
